### ISSUE TITLE
'Download OS' option only shows limited options

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/gnome-boxes#17]
The gnome-boxes in stable currently doesn't show any OS's other than Gnome OS. If you search for ubuntu, nothing is found.

![image](https://github.com/ubuntu/gnome-boxes/assets/12970280/4c0d5b5b-abd1-4869-97e6-7359a0952e87)

**Comment by sergio-costas** [comment]
Is it already published? I'm trying with "edge" and it works fine...

**Comment by hellsworth** [comment]
We determined that the version in `edge` (42.0.1-2-geb985ee1fd, Rev 1) shows the expected distro list:
![image](https://github.com/ubuntu/gnome-boxes/assets/12970280/496abb01-7446-4562-a87b-193da95aceda)

The interim version in `stable` (42.3, Rev 4) also shows the exptected distro list.

But the newer version in `candidate` does (44.2, Rev 7) only shows GNOME OS (as shown in the description image).
